# Generated by Django 3.2.5 on 2021-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puplisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher.', max_length=50)),
                ('website', models.URLField(help_text="The publisher's website link.")),
                ('email', models.EmailField(help_text="The publisher's contact email address.", max_length=254)),
            ],
        ),
    ]
