# Generated by Django 3.2.5 on 2021-09-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210901_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puplisher',
            new_name='Publisher',
        ),
    ]
